# Netlify configuration file for React/Vite SPA

[build]
  # Build command for Vite
  command = "npm run build"
  
  # Directory where the build output is located
  publish = "dist"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Optional: Force HTTPS
# [[redirects]]
#   from = "http://royavalet.netlify.app/*"
#   to = "https://royavalet.netlify.app/:splat"
#   status = 301
#   force = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
